### ISSUE TITLE
Question about "Skip to Main Content"

### ISSUE THREAD

**Issue by dLundrigan** [cenw-wscoe/WCAG-in-Plain-Language#19]
What is considered Main Content? Skip to main content goes to H1, but what if there is content above h1  that is not available to the user? How will a blind user know they missed content above the h1 tag? They would have to use down arrows and know there is something missed.  Would this be a fail or suggestion if not all content is under h1? Is this an example of Usability vs. Accessibility?

**Comment by dLundrigan** [comment]
Please re-word question as needed.
Let me know if any clarifications needed. Site looks great!

**Comment by MaximPerry** [comment]
![image](https://user-images.githubusercontent.com/28932114/178024879-619f07c0-e68b-4ddb-a9c2-07c520523ece.png)
